image: "registry.fedoraproject.org/fedora:35"

before_script:
  - dnf update -y --nogpgcheck
  - dnf install -y --nogpgcheck git gtksourceview4-devel xorg-x11-server-Xvfb
  - git submodule update --init
  - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --default-toolchain none -y
  - source $HOME/.cargo/env
  - rustup toolchain install nightly --profile minimal --allow-downgrade -c rustfmt

stages:
  - test
  - deploy

build:
  stage: test
  script:
    - cargo build --all-features
    - xvfb-run -a -s "-screen 0 1024x768x24" cargo test

pages:
  stage: deploy
  script:
    - cp ./GtkSource-4.gir ./gir-files/
    - cargo run --release -- -c ./sourceview4/Gir.toml -d ./gir-files --doc-target-path docs.md -m doc
    - cargo install rustdoc-stripper
    - /root/.cargo/bin/rustdoc-stripper -g -o ./sourceview4/docs.md
    - cargo doc -p sourceview4 --all-features
    - mv target/doc/ public
  artifacts:
    paths:
      - public
  only:
    refs:
      - master
