// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

use GutterRenderer;
use View;
use glib::object::IsA;
use glib::translate::*;
use gtk;
use gtk_source_sys;
use std::fmt;

glib_wrapper! {
    pub struct Gutter(Object<gtk_source_sys::GtkSourceGutter, gtk_source_sys::GtkSourceGutterClass, GutterClass>);

    match fn {
        get_type => || gtk_source_sys::gtk_source_gutter_get_type(),
    }
}

pub const NONE_GUTTER: Option<&Gutter> = None;

/// Trait containing all `Gutter` methods.
///
/// # Implementors
///
/// [`Gutter`](struct.Gutter.html)
pub trait GutterExt: 'static {
    /// Finds the `GutterRenderer` at (x, y).
    /// ## `x`
    /// The x position to get identified.
    /// ## `y`
    /// The y position to get identified.
    ///
    /// # Returns
    ///
    /// the renderer at (x, y) or `None`.
    fn get_renderer_at_pos(&self, x: i32, y: i32) -> Option<GutterRenderer>;

    ///
    /// # Returns
    ///
    /// the associated `View`.
    fn get_view(&self) -> Option<View>;

    ///
    /// # Returns
    ///
    /// the `gtk::TextWindowType` of `self`.
    fn get_window_type(&self) -> gtk::TextWindowType;

    /// Insert `renderer` into the gutter. If `renderer` is yet unowned then gutter
    /// claims its ownership. Otherwise just increases renderer's reference count.
    /// `renderer` cannot be already inserted to another gutter.
    /// ## `renderer`
    /// a gutter renderer (must inherit from `GutterRenderer`).
    /// ## `position`
    /// the renderer position.
    ///
    /// # Returns
    ///
    /// `true` if operation succeeded. Otherwise `false`.
    fn insert<P: IsA<GutterRenderer>>(&self, renderer: &P, position: i32) -> bool;

    /// Invalidates the drawable area of the gutter. You can use this to force a
    /// redraw of the gutter if something has changed and needs to be redrawn.
    fn queue_draw(&self);

    /// Removes `renderer` from `self`.
    /// ## `renderer`
    /// a `GutterRenderer`.
    fn remove<P: IsA<GutterRenderer>>(&self, renderer: &P);

    /// Reorders `renderer` in `self` to new `position`.
    /// ## `renderer`
    /// a `gtk::CellRenderer`.
    /// ## `position`
    /// the new renderer position.
    fn reorder<P: IsA<GutterRenderer>>(&self, renderer: &P, position: i32);
}

impl<O: IsA<Gutter>> GutterExt for O {
    fn get_renderer_at_pos(&self, x: i32, y: i32) -> Option<GutterRenderer> {
        unsafe {
            from_glib_none(gtk_source_sys::gtk_source_gutter_get_renderer_at_pos(self.as_ref().to_glib_none().0, x, y))
        }
    }

    fn get_view(&self) -> Option<View> {
        unsafe {
            from_glib_none(gtk_source_sys::gtk_source_gutter_get_view(self.as_ref().to_glib_none().0))
        }
    }

    fn get_window_type(&self) -> gtk::TextWindowType {
        unsafe {
            from_glib(gtk_source_sys::gtk_source_gutter_get_window_type(self.as_ref().to_glib_none().0))
        }
    }

    fn insert<P: IsA<GutterRenderer>>(&self, renderer: &P, position: i32) -> bool {
        unsafe {
            from_glib(gtk_source_sys::gtk_source_gutter_insert(self.as_ref().to_glib_none().0, renderer.as_ref().to_glib_none().0, position))
        }
    }

    fn queue_draw(&self) {
        unsafe {
            gtk_source_sys::gtk_source_gutter_queue_draw(self.as_ref().to_glib_none().0);
        }
    }

    fn remove<P: IsA<GutterRenderer>>(&self, renderer: &P) {
        unsafe {
            gtk_source_sys::gtk_source_gutter_remove(self.as_ref().to_glib_none().0, renderer.as_ref().to_glib_none().0);
        }
    }

    fn reorder<P: IsA<GutterRenderer>>(&self, renderer: &P, position: i32) {
        unsafe {
            gtk_source_sys::gtk_source_gutter_reorder(self.as_ref().to_glib_none().0, renderer.as_ref().to_glib_none().0, position);
        }
    }
}

impl fmt::Display for Gutter {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "Gutter")
    }
}
