// This file was generated by gir (https://github.com/gtk-rs/gir)
// from
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

mod buffer;
pub use self::buffer::Buffer;
pub use self::buffer::BufferBuilder;

mod completion;
pub use self::completion::Completion;
pub use self::completion::CompletionBuilder;

mod completion_context;
pub use self::completion_context::CompletionContext;
pub use self::completion_context::CompletionContextBuilder;

mod completion_info;
pub use self::completion_info::CompletionInfo;

mod completion_item;
pub use self::completion_item::CompletionItem;
pub use self::completion_item::CompletionItemBuilder;

mod completion_proposal;
pub use self::completion_proposal::CompletionProposal;

mod completion_provider;
pub use self::completion_provider::CompletionProvider;

mod completion_words;
pub use self::completion_words::CompletionWords;
pub use self::completion_words::CompletionWordsBuilder;

mod file;
pub use self::file::File;
pub use self::file::FileBuilder;

mod file_loader;
pub use self::file_loader::FileLoader;
pub use self::file_loader::FileLoaderBuilder;

mod file_saver;
pub use self::file_saver::FileSaver;
pub use self::file_saver::FileSaverBuilder;

mod gutter;
pub use self::gutter::Gutter;
pub use self::gutter::GutterBuilder;

mod gutter_renderer;
pub use self::gutter_renderer::GutterRenderer;

mod gutter_renderer_pixbuf;
pub use self::gutter_renderer_pixbuf::GutterRendererPixbuf;
pub use self::gutter_renderer_pixbuf::GutterRendererPixbufBuilder;

mod gutter_renderer_text;
pub use self::gutter_renderer_text::GutterRendererText;
pub use self::gutter_renderer_text::GutterRendererTextBuilder;

mod language;
pub use self::language::Language;

mod language_manager;
pub use self::language_manager::LanguageManager;
pub use self::language_manager::LanguageManagerBuilder;

mod map;
pub use self::map::Map;
pub use self::map::MapBuilder;

mod mark;
pub use self::mark::Mark;
pub use self::mark::MarkBuilder;

mod mark_attributes;
pub use self::mark_attributes::MarkAttributes;
pub use self::mark_attributes::MarkAttributesBuilder;

mod print_compositor;
pub use self::print_compositor::PrintCompositor;
pub use self::print_compositor::PrintCompositorBuilder;

mod region;
pub use self::region::Region;
pub use self::region::RegionBuilder;

mod search_context;
pub use self::search_context::SearchContext;
pub use self::search_context::SearchContextBuilder;

mod search_settings;
pub use self::search_settings::SearchSettings;
pub use self::search_settings::SearchSettingsBuilder;

mod space_drawer;
pub use self::space_drawer::SpaceDrawer;
pub use self::space_drawer::SpaceDrawerBuilder;

mod style;
pub use self::style::Style;
pub use self::style::StyleBuilder;

mod style_scheme;
pub use self::style_scheme::StyleScheme;
pub use self::style_scheme::StyleSchemeBuilder;

mod style_scheme_chooser;
pub use self::style_scheme_chooser::StyleSchemeChooser;

mod style_scheme_chooser_button;
pub use self::style_scheme_chooser_button::StyleSchemeChooserButton;

mod style_scheme_chooser_widget;
pub use self::style_scheme_chooser_widget::StyleSchemeChooserWidget;

mod style_scheme_manager;
pub use self::style_scheme_manager::StyleSchemeManager;
pub use self::style_scheme_manager::StyleSchemeManagerBuilder;

mod tag;
pub use self::tag::Tag;
pub use self::tag::TagBuilder;

mod undo_manager;
pub use self::undo_manager::UndoManager;

mod view;
pub use self::view::View;
pub use self::view::ViewBuilder;

mod encoding;
pub use self::encoding::Encoding;

mod enums;
pub use self::enums::BackgroundPatternType;
pub use self::enums::BracketMatchType;
pub use self::enums::ChangeCaseType;
pub use self::enums::CompletionError;
pub use self::enums::CompressionType;
pub use self::enums::FileLoaderError;
pub use self::enums::FileSaverError;
pub use self::enums::GutterRendererAlignmentMode;
pub use self::enums::NewlineType;
pub use self::enums::SmartHomeEndType;
pub use self::enums::ViewGutterPosition;

mod flags;
pub use self::flags::CompletionActivation;
pub use self::flags::FileSaverFlags;
pub use self::flags::GutterRendererState;
pub use self::flags::SortFlags;
pub use self::flags::SpaceLocationFlags;
pub use self::flags::SpaceTypeFlags;

#[doc(hidden)]
pub mod traits {
    pub use super::buffer::BufferExt;
    pub use super::completion::CompletionExt;
    pub use super::completion_context::CompletionContextExt;
    pub use super::completion_item::CompletionItemExt;
    pub use super::completion_proposal::CompletionProposalExt;
    pub use super::completion_provider::CompletionProviderExt;
    pub use super::completion_words::CompletionWordsExt;
    pub use super::file::FileExt;
    pub use super::file_loader::FileLoaderExt;
    pub use super::file_saver::FileSaverExt;
    pub use super::gutter::GutterExt;
    pub use super::gutter_renderer::GutterRendererExt;
    pub use super::gutter_renderer_pixbuf::GutterRendererPixbufExt;
    pub use super::gutter_renderer_text::GutterRendererTextExt;
    pub use super::language::LanguageExt;
    pub use super::language_manager::LanguageManagerExt;
    pub use super::map::MapExt;
    pub use super::mark::MarkExt;
    pub use super::mark_attributes::MarkAttributesExt;
    pub use super::print_compositor::PrintCompositorExt;
    pub use super::region::RegionExt;
    pub use super::search_context::SearchContextExt;
    pub use super::search_settings::SearchSettingsExt;
    pub use super::space_drawer::SpaceDrawerExt;
    pub use super::style_scheme::StyleSchemeExt;
    pub use super::style_scheme_chooser::StyleSchemeChooserExt;
    pub use super::style_scheme_manager::StyleSchemeManagerExt;
    pub use super::tag::TagExt;
    pub use super::undo_manager::UndoManagerExt;
    pub use super::view::ViewExt;
}
