[package]
name = "sourceview4-sys"
version = "0.1.0"
authors = ["Christopher Davis <brainblasted@disroot.org>"]
edition = "2018"
build = "build.rs"

[dependencies]
libc = "0.2"
glib-sys = "0.9.0"
gobject-sys = "0.9.0"
gio-sys = "0.9.0"
gtk-sys = "0.9.0"
gdk-sys = "0.9.0"
gdk-pixbuf-sys = "0.9.0"
cairo-sys-rs = "0.9.0"

[build-dependencies]
pkg-config = "0.3.7"

[dev-dependencies]
shell-words = "0.1.0"
tempdir = "0.3"

[features]
dox = []
