[package]
name = "sourceview4-sys"
version = "0.2.0"
authors = ["Christopher Davis <brainblasted@disroot.org>"]
description = "FFI bindings for GtkSourceView 4"
license = "LGPL-2.1-or-later"
edition = "2018"
documentation = "https://world.pages.gitlab.gnome.org/Rust/sourceview4-rs/sourceview4_sys/"
build = "build.rs"
exclude = ["gir-files/*", "gir/"]
[package.metadata.docs.rs]
features = ["dox"]

[dependencies]
libc = "0.2"
glib-sys = "0.9.1"
gobject-sys = "0.9.1"
gio-sys = "0.9.1"
gtk-sys = "0.9.2"
gdk-sys = "0.9.1"
gdk-pixbuf-sys = "0.9.1"
cairo-sys-rs = "0.9.2"

[build-dependencies]
pkg-config = "0.3.7"

[dev-dependencies]
shell-words = "0.1.0"
tempfile = "3"

[features]
dox = []
