[options]
girs_directories = ["../gir-files", "../"]
work_mode = "sys"
library = "GtkSource"
version = "4"
min_cfg_version = "4"
external_libraries = [
   "Cairo",
   "GLib",
   "GObject",
   "Gio",
   "Gtk",
   "Gdk",
   "GdkPixbuf",
]
