[package]
name = "sourceview4"
version = "0.2.0"
authors = ["Christopher Davis <brainblasted@disroot.org>"]
description = "API bindings for GtkSourceView 4"
license = "LGPL-2.1-or-later"
keywords = ["gtksourceview", "sourceview", "gtk-rs", "gnome"]
repository = "https://gitlab.gnome.org/World/Rust/sourceview4-rs"
documentation = "https://world.pages.gitlab.gnome.org/Rust/sourceview4-rs/sourceview4/"
exclude = ["gir-files/*", "gir/"]

[dependencies]
libc = "0.2.66"
bitflags = "1.2.1"
cairo-rs = "0.8.1"
glib = "0.9.3"
gio = "0.8.1"
gdk = "0.12.1"
gdk-pixbuf = "0.8.0"
pango = "0.8.0"
glib-sys = "0.9.1"
gtk-sys = "0.9.2"
gobject-sys = "0.9.1"
gio-sys = "0.9.1"
gdk-sys = "0.9.1"


[dependencies.gtk]
version = "0.8.1"
features = [ "v3_22" ]

[dependencies.sourceview4-sys]
path = "../sourceview4-sys"

[features]
dox = ["sourceview4-sys/dox"]
